name: Test code and app
on: 
  pull_request:
    branches: [main]
      
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: install dvc
        uses: iterative/setup-dvc@v1
    
      - name: pulling data
        env:
          dags_user: ${{ secrets.USER }}
          dags_password: ${{ secrets.PASSWORD }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user $dags_user
          dvc remote modify origin --local password $dags_password
          dvc pull --remote origin
          
      - name: reproduce model
        run: dvc repro
        
      - name: Iterative CML setup
        uses: iterative/setup-cml@v1
        
      - name: create CML report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          dvc metrics show --show-md >> report.md
          cat dvclive/params.yaml >> report.md
          cml comment create report.md
        
